version: '3.9'
services:
  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=secret
    volumes:
      - redis_data:/data
    command: redis-server --requirepass secret

  redis-commander:
    image: rediscommander/redis-commander:latest
    restart: always
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOST:redis
      - REDIS_PASSWORD=secret
      - HTTP_USER=admin
      - HTTP_PASSWORD=admin
    depends_on:
      - redis

volumes:
  redis_data:
